Update startproject command
dolamroth/starlette-web pull request #65
Opened 2024-01-08 02:41 UTC by Merser4

- Added file templates like in Django
- For the `startproject` command, I added an extended version of file generation that automatically configures `alembic/env.py` and `alembic.ini`. Example `python command.py startproject project_name ----advanced_project_template=true`
- Added function `process_revision_directives` in `alembic/env.py` that generate version files like in Django (0001_*, 0002_*).

2024-01-08 10:49 UTC, dolamroth commented
Честно говоря, эта задача не является актуальной, поскольку сейчас по умолчанию миграции создаются с префиксом даты, т.е. они упорядочены и так.

Можно оставить, но текущее решение надо упростить.

2024-01-08 10:57 UTC, dolamroth requested changes

2024-01-08 10:57 UTC, dolamroth commented on starlette_web/common/conf/file_templates/alembic_env_template.py-tpl
> +import asyncio
Не храни шаблон файла `alembic.ini`, он создается в результате вызова `alembic init`. Вместо этого в команде добавляй в него метод `process_revision_directives` (дополнительный импорт перенеси внутрь метода) и подставляй его в context.configure( ... при перезаписи файла построчно

2024-01-08 10:57 UTC, dolamroth commented on starlette_web/common/conf/file_templates/env_template.py-tpl
> +APP_DEBUG=false
Перенеси файл в директорию _project_defaults, а директорию file_templates удали

2024-01-08 10:57 UTC, dolamroth commented on starlette_web/common/management/commands/startproject.py
> +import starlette_web
Это не нужно

2024-01-08 10:57 UTC, dolamroth commented on starlette_web/common/management/commands/startproject.py
> +        files_templates_dir = Path(starlette_web.__path__[0], "common", "conf", "file_templates")
Бери путь к файлу как раньше из переменной `defaults_dir = Path(__file__).parent / "_project_defaults"`

2024-01-08 10:57 UTC, dolamroth commented on starlette_web/common/management/commands/startproject.py
> +        parser.add_argument("--advanced_project_template", type=str, default="false")
Булевые параметры задавать необходимо по-другому, используя метод store_const

Вот образец https://github.com/dolamroth/starlette-web/blob/main/starlette_web/tests/management/commands/test_parser.py#L15

2024-01-08 10:57 UTC, dolamroth commented on starlette_web/common/management/commands/startproject.py
> +        parser.add_argument("--advanced_project_template", type=str, default="false")
Необходимо поменять имя параметра и назначение. 

`--migration_prefix` = ["auto", "date"] (по умолчанию `auto`)

Поскольку к `advanced` это отношение не имеет

2024-01-08 10:57 UTC, dolamroth commented on starlette_web/common/management/commands/startproject.py
> +        is_advanced_project_template = True if options.get("advanced_project_template") == "true" else False
migration_prefix = options.get("migration_prefix")

2024-01-08 10:57 UTC, dolamroth commented on starlette_web/common/management/commands/startproject.py
> +    async def _setup_advanced_alembic_conf(self, project_dir: Path, alembic_env_template: Path) -> None:
Оставь 1 метод _setup_alembic_conf и внутри него в зависимости от значения migration_prefix добавляй или не добавляй нужные строки

2024-01-08 11:10 UTC, Merser4 commented on starlette_web/common/conf/file_templates/alembic_env_template.py-tpl
> +import asyncio
Это шаблон файла `alembic/env.py`. Я его решил хранить отдельно, так как там много исправлений после стандартной генерации, и получается много некрасивого кода при чтении построчно. Мне казалось лучше перезаписать весь файл. Единственная проблема, сгенерированный файл в некоторых версиях `alembic` может немного отличатся, и нужно будет править либо шаблон, либо код в чтении построчно.

2024-01-08 11:23 UTC, dolamroth commented on starlette_web/common/conf/file_templates/alembic_env_template.py-tpl
> +import asyncio
Ну вот меня беспокоит в основном версионирование этого файла при обновлении alembic (а он от версии к версии отличается).

Также я тестил идею с автогенерируемым методом process_revision_directives, его теоретически можно по какому-нибудь сложному пайплайну генерировать, затем превращать в байткод, записывать в файл, и там распаковывать. А когда у тебя жесткий шаблон, так делать не получится. (Это конечно слишком экзотический кейс, который вряд ли случится, но всё же).

Получится не очень красиво действительно, но ты же для этого и сделал отдельный метод `_setup_alembic_conf`, чтобы туда вынести всё некрасивое?

2024-01-08 11:34 UTC, Merser4 commented on starlette_web/common/conf/file_templates/alembic_env_template.py-tpl
> +import asyncio
Я писал эти 2 метода (`_setup_alembic_**`) для разделения стандартной и расширенной настройки. Основная проблема в версионировании. Как проще поддерживать ее, правками в шаблоне или в команде?

2024-01-08 11:57 UTC, dolamroth commented on starlette_web/common/conf/file_templates/alembic_env_template.py-tpl
> +import asyncio
При правках в шаблоне проще, потому что ты не переписываешь весь шаблон.

2024-01-09 17:47 UTC, Merser4 commented on starlette_web/common/conf/file_templates/alembic_env_template.py-tpl
> +import asyncio
По умолчанию будет генерироваться новый шаблон проекта.

2024-01-09 17:47 UTC, Merser4 commented on starlette_web/common/conf/file_templates/env_template.py-tpl
> +APP_DEBUG=false
Перенес

2024-01-09 17:47 UTC, Merser4 commented on starlette_web/common/management/commands/startproject.py
> +import starlette_web
Удален

2024-01-09 17:47 UTC, Merser4 commented on starlette_web/common/management/commands/startproject.py
> +        files_templates_dir = Path(starlette_web.__path__[0], "common", "conf", "file_templates")
Вернул

2024-01-09 17:49 UTC, Merser4 commented on starlette_web/common/management/commands/startproject.py
> +        parser.add_argument("--advanced_project_template", type=str, default="false")
Сделал как ты сказал, но суть параметра не в настройке префикса, а в виде конфигурации для `alembic`.

2024-01-09 17:50 UTC, Merser4 commented on starlette_web/common/management/commands/startproject.py
> +    async def _setup_advanced_alembic_conf(self, project_dir: Path, alembic_env_template: Path) -> None:
Все в 1 методе.

2024-01-10 13:48 UTC, dolamroth commented on starlette_web/common/conf/file_templates/alembic_env_template.py-tpl
> +import asyncio
Убери целиком шаблон env.py и патчи его как здесь https://github.com/dolamroth/starlette-web/blob/main/starlette_web/common/management/commands/startproject.py#L84

Либо, если хочешь шаблон храни, сделай шаблон Jinja2, в котором в зависимости от условий есть или нет функция `process_revision_directives`

2024-01-10 14:07 UTC, dolamroth commented on starlette_web/common/management/commands/startproject.py
> +        parser.add_argument("--advanced_project_template", type=str, default="false")
Насколько могу судить, параметр функционально только меняет префикс, т.е. его некорректно называть `advanced_project_template`

Если будет потребность как-то ещё модифицировать файл настроек, то за это будет отвечать другой параметр

2024-01-10 14:11 UTC, dolamroth commented on starlette_web/common/management/commands/startproject.py
> +    async def _setup_advanced_alembic_conf(self, project_dir: Path, alembic_env_template: Path) -> None:
Я имел в виду другое. Не то что у тебя будет 1 метод, в которое ты перенесёшь содержимое обоих методов, а то, что ты в 1 методе пропишешь условие "если есть параметр migration_prefix==auto", то вот тут и тут добавить новые строки.

Если делать это через Jinja2 шаблон https://jinja.palletsprojects.com/en/3.1.x/api/#basics, то там соответственно так

```
{% if migration_prefix==auto %}
def process_revision_directives():
    ...
{% endif %}
```

```
context,Context(
    {% if migration_prefix==auto %}process_revision_directives=process_revision_directives
    ...
)
```

2024-01-14 18:55 UTC, merged